agencyportal/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView
from quotes.views import Register

urlpatterns = [
    # path('testpage', TemplateView.as_view(template_name='pages/page.html')),
    path('admin/', admin.site.urls),
    path('register/success/',TemplateView.as_view(template_name="registration/success.html"), name ='register-success'),
    path('register/', Register.as_view(), name='register'),
    path('quote/', include('quotes.urls')),
    path('', include('django.contrib.auth.urls')),
    path('', include('pages.urls')),
    
]

pages/urls.py
from django.urls import path
from . import views
from django.views.generic.base import TemplateView

urlpatterns = [
     path('testpage', TemplateView.as_view(template_name='pages/page.html')),
   # path('', views.index, name = 'index'),
     path('', views.index, {'pagename': ''}, name='home'),
     path('contact', views.contact, name='contact'),
     path('<str:pagename>', views.index, name='index'),      

]

quotes/urls.py
from django.urls import path
from . import views

from .views import QuoteList, QuoteView

urlpatterns = [
    
 path('', views.quote_req, name='quote-request'),
 path('show/<int:pk>', QuoteView.as_view(),name='quote-detail'),
 path('show', QuoteList.as_view(), name='show-quotes'),

 

]

pages/models.py
from django.db import models

# Create your models here.

class Page(models.Model):

    title= models.CharField(max_length=60 )
    permalink=models.CharField(max_length=12, unique=True)
    update_date=models.DateTimeField('Last Updated')
    bodytext = models.TextField('Page Content',blank=True)


    def __str__(self):
        return self.title

quotes/models.py
# Create your models here.
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

STATUS_CHOICES = (
('NEW', 'New Site'),
('EX', 'Existing Site'),
)

PRIORITY_CHOICES = (
('U', 'Urgent - 1 week or less'),
('N', 'Normal - 2 to 4 weeks'),
('L', 'Low - Still Researching'),
)

class Quote(models.Model):
    name = models.CharField(max_length=100)
    position = models.CharField(max_length=60,blank=True)
    company = models.CharField(max_length=60,blank=True)
    address = models.CharField(max_length=200,blank=True)
    phone = models.CharField(max_length=30, blank=True)
    email = models.EmailField()
    web = models.URLField(blank=True)
    description = models.TextField()
    sitestatus = models.CharField(max_length=20,choices=STATUS_CHOICES)
    priority = models.CharField(max_length=40,choices=PRIORITY_CHOICES)
    jobfile = models.FileField(upload_to='uploads/',blank=True)
    submitted = models.DateField(auto_now_add=True)
    quotedate = models.DateField(blank=True, null=True)
    quoteprice = models.DecimalField(decimal_places=2,max_digits=7, blank=True, default=0)
    budget = models.DecimalField(decimal_places=2,max_digits=7, blank=True, default=0)
    username = models.ForeignKey(User, blank=True,null=True, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.id)

pages/forms.py
from django import forms




class ContactForm(forms.Form):
    yourname = forms.CharField(max_length=100,label='Your Name')
    email = forms.EmailField(required=False,label='Your e-mail address')
    #phonenumber = forms.CharField(max_length=15, required=False, label='Phone')
    subject = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)

quotes/forms.py
from django import forms
from django.forms import ModelForm
from .models import Quote



class QuoteForm(ModelForm):
    required_css_class = 'required'
    class Meta:
            model = Quote
            fields = [
            'name', 'position', 'company', 'address',
            'phone', 'email', 'web', 'description','budget',
            'sitestatus', 'priority', 'jobfile'
            ]

pages/views.py
from django.shortcuts import render,get_object_or_404
from django.core.mail import send_mail, get_connection


from django.http import HttpResponse, HttpResponseRedirect

# Create your views here.
from .models import Page
from .forms import ContactForm


def index(request,pagename):
   #return HttpResponse("<h1>The  Homepage</h1>")
   pagename = '/' + pagename
  # pg = Page.objects.get(permalink=pagename)
   pg = get_object_or_404(Page, permalink = pagename)
   context = {
      'title':pg.title,
      'content': pg.bodytext,
      'last_updated': pg.update_date,
      'page_list': Page.objects.all(),

   }

   #assert False


   return render(request, 'pages/page.html',context)

def contact(request):
   submitted = False

   if request.method == 'POST':

      form = ContactForm(request.POST)

      if form.is_valid():

         cd = form.cleaned_data
         con = get_connection('django.core.mail.backends.console.EmailBackend')
         send_mail(
            cd['subject'],
            cd['message'],
            cd.get('email', 'noreply@example.com'),['siteowner@example.com'],
            connection=con
            
         )

         #assert False
        
         


         return HttpResponseRedirect('/contact?submitted=True')

   else:

      form = ContactForm()

      if 'submitted' in request.GET:

         submitted = True

   return render(request, 'pages/contact.html',{'form': form, 'page_list': Page.objects.all(),'submitted': submitted})
   

quotes/views.py
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy

# Create your views here.
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import Quote
from .forms import QuoteForm
from pages.models import Page


from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin



        

class QuoteView(DetailView,LoginRequiredMixin):
        login_url = reverse_lazy('login')
        #model = Quote
        context_object_name = 'quote'
        def get_queryset(self):
            return Quote.objects.filter(username=self.request.user)

        def get_context_data(self, **kwargs):
                context = super(QuoteView, self).get_context_data(**kwargs)
                context['page_list'] = Page.objects.all()
                return context


class QuoteList(LoginRequiredMixin,ListView):
    login_url = reverse_lazy('login')
    #model = Quote
    context_object_name = 'all_quotes'

    def get_queryset(self):
        return Quote.objects.filter(username=self.request.user)

    def get_context_data(self, **kwargs):
        context = super(QuoteList, self).get_context_data(**kwargs)
        context['page_list'] = Page.objects.all()
        return context


class Register(CreateView):
    template_name = 'registration/register.html' 
    form_class = UserCreationForm
    success_url = reverse_lazy('register-success')

    def form_valid(self, form):
        form.save()
        return HttpResponseRedirect(self.success_url)



@login_required(login_url=reverse_lazy('login'))
def quote_req(request):

    submitted = False
    if request.method == 'POST':
        form = QuoteForm(request.POST, request.FILES)
        if form.is_valid():
            quote = form.save(commit=False)
            try:
                quote.username = request.user
            except Exception:
                pass
            form.save()
            return HttpResponseRedirect('/quote/?submitted=True')
    else:
        form = QuoteForm()
        if 'submitted' in request.GET:
            submitted = True
    return render(request, 'quotes/quote.html',{'form': form, 'page_list': Page.objects.all(), 'submitted': submitted})

pages/templates/pages/contact.html
{% extends "pages/page.html" %}

{% block title %}{% endblock title %}

{% block content %}

<h1>Contact us</h1>

{% if submitted %}
    <p class="success">
    Your message was submitted successfully. Thankyou
    </p>
{% else %}

    <form action="" method="post" novalidate>

    <table>

    {{ form.as_table }}

    <tr>

    <td>&nbsp;</td>

    <td><input type="submit" value="Submit"></td>

    </tr>

    </table>

    {% csrf_token %}

    </form>
{% endif %}
{% endblock content %}

pages/templates/pages/page.html

{% extends "base.html" %}
{% load static %}

{% block title %}{% endblock title %}

{% block sidenav %}
{% for page in page_list %}
  
 <a href="{{ page.permalink }}">{{ page.title }}</a>


{% endfor %}
{% endblock sidenav %}







{% block content %}

{% autoescape off %}
  {{content}}
{% endautoescape %}
<p>
   Page last updated: {{ last_updated|date:"D d F Y" }}
  </p>
{% endblock content %}



pages/templates/pages/t.html
{% block title %}{{title}}{% endblock title %}
<br>
{% block content %}

{{content}}
{% endblock content %}
<br>

{% block date %}{{last_updated}}{% endblock date %}

quotes/templates/quotes/quote.html
{% extends "base.html" %}

{% block title %}{% endblock title %}

{% block sidenav %}

    {% for page in page_list %}
        <li><a href="{{ page.permalink }}">{{ page.title }}</a></li>
    {% endfor %}

{% endblock sidenav %}

{% block content %}
 <h1>Quote Request</h1>

{% if submitted %}

    <p class="success">

        Your quote was submitted successfully. Thankyou.
    </p>

{% else %}

    <form action="" enctype="multipart/form-data" method="post" novalidate>

    <table>

    {{ form.as_table }}

    <tr>

    <td>&nbsp;</td>

    <td><input type="submit" value="Submit"></td>


    </tr>

    </table>

    {% csrf_token %}

    </form>
{% endif %}
{% endblock content %}

quotes/templates/quotes/quote_detail.html
<style>

 .quote td:first-child {
    background-color: #4c4c4c;
    color: white;
    text-align: right;
    padding: 8px 5px;
    border: none;
    }
    .quote td {
    padding: 5px 10px;
    }
</style>

{% extends "quotes/quote.html" %}
{% block title %}All Quotes{% endblock title %}
{% block content %}
<h1>Quote Detail</h1>
<table class="quote">
<tr><td>ID:</td><td>{{ quote.id }}</td></tr>
<tr><td>Name:</td><td>{{ quote.name }}</td></tr>
<tr><td>Company:</td><td>{{ quote.company }}</td></tr>
<tr><td>Email:</td><td>{{ quote.email }}</td></tr>
<tr><td>Web Address:</td><td>{{ quote.web }}</td></tr>
<tr><td>Job Description:</td><td>{{ quote.description}}</td></tr>
<tr><td>Site Status:</td><td>{{ quote.get_sitestatus_display }}</td></tr>
<tr><td>Priority:</td><td>{{ quote.get_priority_display }}</td></tr>
<tr><td>Submit Date:</td><td>{{ quote.submitted|date:"m-d-y" }}</td></tr>
<tr><td>Quote Date:</td><td>{{ quote.quotedate|date:"m-d-y"|default:"pending" }}</td></tr>
<tr><td>Quote Price:</td><td>{{ quote.quoteprice|default:"--" }}</td></tr>
</table>
<p><a href="../show">Back to quote list</a></p>
{% endblock content %}

quotes/templates/quotes/quote_list.html
<style>

    .quotehdr th {
        background-color: #4c4c4c;
        color: white;
        text-align: center;
        padding: 8px 5px;
        border: none;
        }
        .quoterow td {
        padding: 5px 10px;
        }
        .altrow {
        background-color: #e0e0e0
        }
</style>
{% extends "quotes/quote.html" %}





{% block title %}{% endblock title %}


{% block content %}
<h1>All Quotes</h1>
<table style="border-collapse:collapse">
<tr class="quotehdr"><th>ID</th><th>Client Name
</th>
<th>Company</th><th>Submitted</th>
<th>Quoted</th><th>Quote Price</th>
</tr>
{% for quote in all_quotes %}
<tr class="quoterow {% cycle '' 'altrow' %}">
<td><a href="show/{{ quote.id }}">{{ quote.id }}</a></td>
<td>{{ quote.name }}</td>
<td>{{ quote.company }}</td>
<td>{{ quote.submitted|date:"m-d-y" }}</td>
<td>{{ quote.quotedate|date:"m-d-y"|default:"pending" }}</td>
<td>{{ quote.quoteprice|default:"--" }}
</td>
</tr>
{% endfor %}
</table>
{% endblock content %}

templates/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        {% block title %}
        
        {% endblock title %}
       
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href={% static '/assets/favicon.ico' %} />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" type="text/css" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href={% static "/css/styles.css" %} rel="stylesheet" />
  </head>







<body>
    

  <!-- Navigation-->
  <nav class="navbar navbar-light bg-light static-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">Agency Portal</a>
   
       
    

        {% block sidenav %}
        {% endblock sidenav %}

        <a href="/contact">Contact Us</a>
        <a href="/quote/">Get a Quote</a>
        <a href="/quote/show">Show Quotes</a>
        <div id="logo"><img src=""alt=""/>
            
            <span style="float: right;">
            
            {% if user.is_authenticated %}
            
              Hello, {{ user.username }}. <a href="{% url 'logout' %}?next=/">Log out</a>.
            
            {% else %}

              Not logged in. <a href="{% url 'login' %}?next=/">Log in</a>.
            
            
            
            {% endif %}
            
            </span> 
            
            </div>

    </div>
  </nav>
    <header class="">

    </header>
    
   
    <section id="main">
      {% block content %}
      
        <h1>Welcome!</h1>
        <p>This is the site template</p>
        
      {% endblock content %}
      
      
    </section>
   
    <!-- Footer-->
    <footer class="footer bg-light">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 h-100 text-center text-lg-start my-auto">
                    <ul class="list-inline mb-2">
                        {% for page in page_list %}
                        <li class="list-inline-item"><a href={{page.permalink}}>{{page.title}}</a></li>
                        {% endfor %}
                        <li class="list-inline-item"><a href="/contact">Contact Us</a></li>
                        <li class="list-inline-item"><a href="/quote/">Get a Quote</a></li>
                       
                    </ul>
                    <p class="text-muted small mb-4 mb-lg-0">&copy; Your Website 2021. All Rights Reserved.</p>
                </div>
                <div class="col-lg-6 h-100 text-center text-lg-end my-auto">
                    <ul class="list-inline mb-0">
                        <li class="list-inline-item me-4">
                            <a href="#!"><i class="bi-facebook fs-3"></i></a>
                        </li>
                        <li class="list-inline-item me-4">
                            <a href="#!"><i class="bi-twitter fs-3"></i></a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#!"><i class="bi-instagram fs-3"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>
   
  </div>
</body>
</html>
<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
<!-- Core theme JS-->
<script src={% static 'js/scripts.js' %}></script>
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
<!-- * *                               SB Forms JS                               * *-->
<!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
<script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>